
version: '3'

services:
  token-server:
    image: ripperdev/alitoken-server:v0.1.1
    restart: always
    container_name: token-server
    environment:
      RUST_LOG: "info"
    ports:
      - "8080:8080"
